"""tablename on UserModel

Revision ID: 1d1aa16c6493
Revises: 8201c4bef5d4
Create Date: 2026-09-28 17:53:27.473873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1aa16c6493'
down_revision = '8201c4bef5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('passphrase', sa.String(length=512), server_default='NULL', nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_model.id'], name=op.f('fk_users_tenant_id_tenant_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_model_tenant_id'))

    op.drop_table('user_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('passphrase', sa.VARCHAR(length=512), server_default=sa.text("'NULL'"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_model.id'], name=op.f('fk_user_model_tenant_id_tenant_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_model'))
    )
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_model_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
