"""user passphrase

Revision ID: 8201c4bef5d4
Revises: 9017567c777b
Create Date: 2026-09-28 17:27:05.868075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8201c4bef5d4'
down_revision = '9017567c777b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passphrase', sa.String(length=512), server_default='NULL', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_column('passphrase')

    # ### end Alembic commands ###
