"""initialize

Revision ID: 9017567c777b
Revises: 
Create Date: 2026-09-27 16:34:13.944608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9017567c777b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_model'))
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_model.id'], name=op.f('fk_user_model_tenant_id_tenant_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_model'))
    )
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_model_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_model_tenant_id'))

    op.drop_table('user_model')
    op.drop_table('tenant_model')
    # ### end Alembic commands ###
